import Head from 'next/head';
import router from 'next/router';
import { v4 as uuidv4 } from 'uuid';
import React, { useEffect, useRef, useState } from 'react';
import { io, Socket } from 'socket.io-client';
import Message from '../../../../types/Message';
import User from '../../../../types/User';
import clsx from 'clsx';
import UserList from '@/components/UserList';

const socket = io('http://localhost:8000');
type Props = {};
const index = (props: Props) => {
	const [message, setMessage] = useState('');
	const [users, setUsers] = useState<User[]>([]);
	const [messages, setMessages] = useState<Message[]>([]);
	const [username, setUsername] = useState<string | null>(null);
	const [loading, setLoading] = useState(true);
	useEffect(() => {
		const user = localStorage.getItem('username');
		if (!user || user.length == 0) {
			router.replace('/');
		} else {
			setUsername(user);
			setLoading(false);
		}
	}, []);
	useEffect(() => {
		console.log('useeffect ran');
		socket.connect();
		socket.on('connect', () => {
			socket.emit('newUser', {
				userName: localStorage.getItem('username'),
				socketID: socket.id,
			});
		});
		console.log(socket.active);
		return () => {
			socket.disconnect();
		};
	}, []);

	useEffect(() => {
		socket.on('messageResponse', (data: Message) => {
			let newmessages = [...messages];
			newmessages.push.apply(newmessages, [data]);
			setMessages([...newmessages]);
		});
	}, []);

	const onLeaveChat = () => {
		try {
			localStorage.removeItem('username');
			setUsername('');
			socket.disconnect();
			router.replace('/');
		} catch (error) {}
	};
	if (loading) {
		return null;
	}
	return (
		<>
			<Head>
				<title>Chat Application</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div className='h-screen bg-gray-200 flex p-5'>
					<UserList socket={socket} />
					<div className='flex flex-col w-full h-full'>
						<div className='flex flex-row items-center justify-between'>
							<p className='text-2xl'>Chattting right now {username}</p>
							<button
								className='px-4 py-2 bg-red-400 hover:bg-red-600'
								onClick={onLeaveChat}>
								LEAVE CHAT
							</button>
						</div>
						<div className='flex flex-col h-full space-y-5 border border-green-500 p-4 m-1'>
							{messages.map(({ id, name, message }) => (
								<div key={id}>
									<div>{name}</div>
									<div>{message}</div>
								</div>
							))}
						</div>
						<div className='flex space-x-2 m-1'>
							<textarea
								value={message}
								onChange={(e) => setMessage(e.target.value)}
								className='w-full resize-none p-2'
							/>
							<button
								onClick={() => {
									socket.emit('message', {
										message: message,
										name: username,
										socketID: socket.id,
										id: uuidv4(),
									});
									setMessage('');
								}}
								className='bg-green-400 text-white px-4 py-2'>
								Send message
							</button>
						</div>
					</div>
				</div>
			</main>
		</>
	);
};

export default index;
