import Head from 'next/head';
import router from 'next/router';
import React, { useEffect, useState } from 'react';
import { io, Socket } from 'socket.io-client';

const socket = io('http://localhost:8000');

type Props = {};
const index = (props: Props) => {
	const [username, setUsername] = useState<string | null>(null);
	const [loading, setLoading] = useState(true);
	useEffect(() => {
		const user = localStorage.getItem('username');
		if (!user || user.length == 0) {
			router.replace('/');
		} else {
			setUsername(user);
			setLoading(false);
		}
	}, []);
	useEffect(() => {
		socket.on('connect', () => console.log('connected'));
		socket.emit('message', () => console.log('sent message'));
	}, []);
	const onLeaveChat = () => {
		try {
			localStorage.removeItem('username');
			setUsername('');
			router.replace('/');
		} catch (error) {}
	};
	if (loading) {
		return null;
	}
	return (
		<>
			<Head>
				<title>Chat Application</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div className='h-screen bg-gray-200 flex p-5'>
					<div className='flex flex-col px-6'>
						<h1 className='font-bold text-2xl'>Active Users</h1>
						<p>User 1</p>
						<p>User 2</p>
					</div>
					<div className='flex flex-col w-full h-full'>
						<div className='flex flex-row items-center justify-between'>
							<p className='text-2xl'>Chattting right now</p>
							<button
								className='px-4 py-2 bg-red-400 hover:bg-red-600'
								onClick={onLeaveChat}>
								LEAVE CHAT
							</button>
						</div>
						<div className='flex flex-col h-full space-y-5 border border-green-500 p-4 m-1'>
							<p className='self-end'>Messages</p>
							<p>Messages</p>
							<p>Messages</p>
							<p>Messages</p>
						</div>
						<div className='flex space-x-2 m-1'>
							<textarea className='w-full resize-none p-2' />
							<button className='bg-green-400 text-white px-4 py-2'>
								Send message
							</button>
						</div>
					</div>
				</div>
			</main>
		</>
	);
};

export default index;
