import useLocalStorage from '@/hooks/useLocalStorage';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { redirect, useRouter } from 'next/navigation';
export default function Home() {
	const router = useRouter();
	const [username, setUsername] = useState('');
	useEffect(() => {
		let localusername = localStorage.getItem('username');
		localusername = localusername ?? '';
		setUsername(localusername);
		if (localusername.length > 0) {
			router.push('/chat');
		}
	}, []);
	return (
		<>
			<Head>
				<title>Chat Application</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<div className='w-screen h-screen bg-gray-200 flex flex-col items-center justify-center space-y-5'>
					<h1 className='font-bold text-2xl'>Choose your username</h1>
					<div className='flex flex-col items-center space-y-5'>
						<input
							type='text'
							minLength={6}
							name='username'
							id='username'
							className='w-52 h-8 px-4 py-2'
							value={username}
							onChange={(e) => {
								setUsername(e.target.value);
							}}
						/>
						<button
							className='bg-green-400 hover:bg-green-600 rounded-md px-4 py-2'
							onClick={() => {
								if (username.length > 0) {
									localStorage.setItem('username', username);
									router.push('/chat');
								} else {
								}
							}}>
							LOGIN
						</button>
					</div>
				</div>
			</main>
		</>
	);
}
